name: 'PR Close'
on:
  workflow_call:
    secrets:
      auto_version_bump_github_token:
        required: true

jobs:
  merge_pr:
    name: 'PR Merged'
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.AUTO_VERSION_BUMP_GITHUB_TOKEN }}
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
      - name: Git config
        run: |
          git config --global user.email "vmit-dev-l@cornell.edu"
          git config --global user.name "Github Auto Version Bump"
      - name: Apply version bump (major)
        if: contains(github.event.pull_request.labels.*.name, 'major')
        run: npm version major
      - name: Apply version bump (minor)
        if: contains(github.event.pull_request.labels.*.name, 'minor')
        run: npm version minor
      - name: Apply version bump (patch)
        if: ${{ !contains(github.event.pull_request.labels.*.name, 'major') || !contains(github.event.pull_request.labels.*.name, 'minor') }}
        run: npm version patch
      - name: Git push version bump
        # run: git push origin HEAD:${{ github.head_ref }} --follow-tags --force
        run: git push origin --follow-tags --force
      - id: set-version
        name: Output version change
        run: npm pkg get version
