name: build-and-publish-node-package
on:
  workflow_call:
    inputs:
      webtier:
        required: true
        type: string
      node_version:
        required: true
        type: string

jobs:
  build-and-publish-node-package:
    runs-on: ubuntu-latest
    environment: ${{ inputs.webtier }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: ${{ inputs.node_version }}
          registry-url: 'https://npm.pkg.github.com'
          # Defaults to the user or organization that owns the workflow file
          scope: '@cuvmit'
          cache: 'yarn'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache node modules
        uses: actions/cache@v5
        env:
          cache-name: cache-node-modules
        with:
          path: ./node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: build
        run: yarn build:${{ inputs.webtier }}

      - name: set package version
        run:
          echo PACKAGE_VERSION=$(jq --raw-output ".version" package.json) >>
          $GITHUB_ENV

      - name: set main version for sb
        run: |
          echo VERSION=${{ env.PACKAGE_VERSION }}-beta.${{ github.run_number }} >> $GITHUB_ENV
          echo PACKAGE_TAG=beta >> $GITHUB_ENV
        if: ${{ inputs.webtier == 'sb'}}

      - name: set main version for prod
        run: |
          echo VERSION=${{ env.PACKAGE_VERSION }} >> $GITHUB_ENV
          echo PACKAGE_TAG=latest >> $GITHUB_ENV
        if: ${{ inputs.webtier == 'prod'}}

      - name: Change version in package.json
        run: yarn version --no-git-tag-version --new-version ${{ env.VERSION }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: npm publish --tag ${{ env.PACKAGE_TAG }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
