name: build-and-publish-angular-libraries
on:
  workflow_call:
    inputs:
      webtier:
        required: true
        type: string
      node_version:
        required: true
        type: string

jobs:
  build-and-publish-angular-libaries:
    runs-on: ubuntu-latest
    environment: ${{ inputs.webtier }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 2

      - uses: actions/setup-node@v6
        with:
          node-version: ${{ inputs.node_version }}
          registry-url: 'https://npm.pkg.github.com'
          # Defaults to the user or organization that owns the workflow file
          scope: '@cuvmit'
          cache: 'yarn'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: set main version suffix for sb and fetch main refs
        run: |
          echo VERSION_PREID=beta.${{ github.run_number }} >> $GITHUB_ENV
          echo VERSION_MODIFIER=prerelease >> $GITHUB_ENV
          echo PACKAGE_TAG=beta >> $GITHUB_ENV
          git fetch origin main
        if: ${{ inputs.webtier == 'sb'}}

      - name: set main version suffix for prod
        run: |
          echo VERSION_PREID=rc >> $GITHUB_ENV
          echo VERSION_MODIFIER=patch >> $GITHUB_ENV
          echo PACKAGE_TAG=latest >> $GITHUB_ENV
        if: ${{ inputs.webtier == 'prod'}}

      - name: set package versions
        run:
          yarn exec:${{ inputs.webtier }} -- npm version --no-git-tag-version
          --no-workspaces-update --preid=${{ env.VERSION_PREID }} ${{
          env.VERSION_MODIFIER }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: build
        run: yarn build:${{ inputs.webtier }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Package to Github Registry
        run: |
          for pkg in $(find dist -name package.json -maxdepth 3); do
            npm publish $(dirname ${pkg}) --tag ${{ env.PACKAGE_TAG }}
          done
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
